/*
 * generated by Xtext
 */
package mm.ecxt.scoping;

import static mm.ecxt.scoping.MMHelpers.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.FilteringScope;

import com.google.common.base.Predicate;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and when to use it.
 */
public class MMLanguageScopeProvider extends AbstractDeclarativeScopeProvider {

	@Override
	public IScope getScope(final EObject context, EReference reference) {
		Predicate<IEObjectDescription> filter = new Predicate<IEObjectDescription>() {
			@Override
			public boolean apply(IEObjectDescription input) {
				return isValidReferenceAccordingToScopingRules(context, input.getEObjectOrProxy());
			}
		};
		return new FilteringScope(super.getScope(context, reference), filter);
	}

}
