/*
 * generated by Xtext
 */
package mm.ecxt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MMLanguageUiModule extends mm.ecxt.ui.AbstractMMLanguageUiModule {
	public MMLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
