/*
 * generated by Xtext
 */
package mm.ecxt.ui.contentassist

import mm.ecxt.ui.contentassist.AbstractMMLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MMLanguageProposalProvider extends AbstractMMLanguageProposalProvider {
}
