/*
 * generated by Xtext
 */
package mm.ecxt.ui.contentassist

import mm.ecxt.ui.contentassist.AbstractMMLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MMLanguageProposalProvider extends AbstractMMLanguageProposalProvider {
}
