/*
* generated by Xtext
*/
package mm.ecxt;

import mm.ecxt.MMLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MMLanguageStandaloneSetup extends MMLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new MMLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

