/*
 * generated by Xtext
 */
package mm.ecxt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MMLanguageRuntimeModule extends mm.ecxt.AbstractMMLanguageRuntimeModule {

}
