/*
 * generated by Xtext
 */
package mm.ecxt;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MMLanguageStandaloneSetup extends MMLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new MMLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

